export default {
  tabIconDefault: "#858585",
  tabIconSelected: "#010101",
  homeBackgroundColor : "white",
  searchBarColor : "#EFEFEF",
  separateViewColor : "#F9F9F9",
  placeHolderColor : "#909090",
  boxShadowColor : "#F2F2F2",
  greenColor : "#05AF5D",
  disabledGreenColor : "#D4DAD7",
  lightGreenColor : "#36BC7B",
  lighterGreenColor : "#E7F9F0",
  greyColor: "#E0E0E0",
  lightGreyColor: "#ACACAC",
  darkGreyColor: "#5A5A5A",
  blackColor: "#3B3B3B",
  warningColor : "#f0ad4e",
  dangerColor : "#d9534f",
  blueColor : "#1A7FC6",
  leftBoxColor: "#FDDCFD",
  rightBoxColor: "#B2FAFF",
};
