export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const STATUS_UPDATE = 'STATUS_UPDATE';
export const SUBSCRIBE = 'SUBSCRIBE';
export const COORDINATE_UPDATE = 'COORDINATE_UPDATE';

export const RECEIVE_CURRENT_ORDER = 'RECEIVE_CURRENT_ORDER';
export const RECEIVE_PENDING_ORDER = 'RECEIVE_PENDING_ORDER';
export const ACCEPT_ORDER = 'ACCEPT_ORDER';
export const COMPLETE_ORDER = 'COMPLETE_ORDER';
